CREATE TABLE `hkex_futures` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL COMMENT '交易日',
  `tp` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '交易时段',
  `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品种名称',
  `code` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品种代码',
  `con` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '到期日',
  `ls` float DEFAULT NULL COMMENT '最后成交价',
  `nc` float DEFAULT NULL COMMENT '变动',
  `se` float DEFAULT NULL COMMENT '昨结算',
  `bd` float DEFAULT NULL COMMENT '买入价',
  `as` float DEFAULT NULL COMMENT '卖出价',
  `op` float DEFAULT NULL COMMENT '开盘价',
  `hi` float DEFAULT NULL COMMENT '最高价',
  `lo` float DEFAULT NULL COMMENT '最低价',
  `vo` float DEFAULT NULL COMMENT '成交数量',
  `oi` float DEFAULT NULL COMMENT '未平仓合约',
  `last_update` datetime DEFAULT NULL COMMENT '最近交易于',
  `gtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  `extra` text COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '附加字段',
  `run_id` bigint(20) unsigned DEFAULT NULL COMMENT '批次ID',
  `batch_date` datetime DEFAULT NULL COMMENT '运行批次',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_run_id` (`run_id`),
  KEY `idx_batch_date` (`batch_date`),
  UNIQUE KEY `uq_date_tp` (`date`,`tp`,`con`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='港交所_指数期货';