SELECT website as '网站名', count(*) as '数据量' FROM think_tank_detail2 WHERE website in (
"38 North"
,"Acton Institute"
,"Allegheny Institute for Public Policy"
,"American Action Network"
,"American Civil Rights Union"
,"American Enterprise Institute for Public Policy Research (AEI)"
,"American Institute for Economic Research"
,"American Israel Public Affairs Committee"
,"American Iranian Council"
,"American Foreign Policy Council (AFPC)"
,"American Security Council Foundation"
,"Analysis Group"
,"Atlantic Council"
,"Atlas Network"
,"Berggruen Institute"
,"Beacon Hill Institute"
,"Berkeley Roundtable on the International Economy (BRIE)"
,"Belfer Center for Science and International Affairs"
,"Bipartisan Policy Center"
,"Buckeye Institute"
,"Carnegie Council for Ethics in International Affairs"
,"Carnegie Endowment for International Peace (CEIP)"
,"Adam Smith Institute (ASI)"
,"Africa Research Institute (ARI)"
,"Bow Group"
,"Bruges Group"
,"CANZUK International"
,"Centre for Cities"
,"Centre for Economic Policy Research (CEPR)"
,"Centre for London"
,"Centre for Policy Studies (CPS)"
,"Centre for the Economics of Education (CEE)"
,"Chatham House"
,"European Council on Foreign Relations (ECFR)"
,"Foreign Policy Centre (FPC)"
,"Green Alliance"
,"Hansard Society"
,"Institute for Government"
,"Institute for Fiscal Studies (IFS)"
,"Institute for Jewish Policy Research"
,"Institute for Strategic Dialogue"
,"Institute of Economic Affairs (IEA)"
,"International Institute for Strategic Studies (IISS)"
,"LSE IDEAS"
,"Localis"
,"Joseph Rowntree Foundation"
,"National Institute of Economic and Social Research"
,"New City Initiative"
,"New Policy Institute"
,"Open Europe"
,"Polar Research and Policy Initiative"
,"Policy Connect"
,"Asian Development Bank"
,"Daiwa Institute of Research Group (DIR）"
,"Economic Research Institute for Northeast Asia (ERINA)"
,"Fujitsu Research Institute（FRI）"
,"Genron NPO (言論ＮＰＯ)"
,"Hitachi Research Institute（HRI)"
,"Institute of Developing Economies, Japan External Trade Organization(IDE-JETRO)"
,"Institute for International Socio-Economic Studies (IISE)"
,"Economic and Social Research Institute"
,"Japan Institute of International Affairs (JIIA)"
,"Mitsubishi UFJ Research and Consulting"
,"Mizuho Research Institute"
,"Nakasone Yasuhiro Peace Institute"
,"National Institute for Research Advancement"
,"NLI Research Institute"
,"Nomura Research Institute （NRI）"
,"Research Institute of Economy, Trade and Industry (RIETI)"
,"United Nations University (UNU)"
,"Sumitomo Mitsui Trust Research Institute"
,"Center for European Economic Research (ZEW)"
,"Centre for European Policy"
,"Friedrich Ebert Foundation"
,"Atlantic Community"
,"Friedrich Naumann Foundation"
,"German Council on Foreign Relations"
,"German Institute for International and Security Affairs (SWP)"
,"German Institute of Global and Area Studies"
,"German Institute for Economic Research (DIW)"
,"Heinrich Böll Foundation"
,"Kiel Institute for the World Economy (IfW)"
,"Konrad Adenauer Foundation"
,"Ifo Institute - Leibniz Institute for Economic Research"
,"Stiftung Neue Verantwortung"
,"Rosa Luxemburg Foundation"
,"Peace Research Institute Frankfurt"
,"Walter Eucken Institut"
,"Australian Strategic Policy Institute (ASPI)"
,"Centre for Independent Studies (CIS)"
,"Committee for Economic Development of Australia (CEDA)"
,"Centre for Policy Development"
,"East Asian Bureau of Economic Research (EABER)"
,"Development Policy Centre"
,"Lowy Institute"
,"Grattan Institute"
,"Mannkal Economic Education Foundation"
,"Institute of Public Affairs (IPA)"
,"Strategic and Defence Studies Centre (SDSC)"
,"Prosper Australia"
,"The Australia Institute"
,"Per Capita"
,"Center for Immigration Studies"
,"Center for Freedom and Prosperity (CFP)"
,"Center for Automotive Research (CAR)"
,"Ripon Society"
,"Rockefeller Institute of Government"
,"Roosevelt Institute Campus Network"
,"Seven Pillars Institute"
,"Show-Me Institute"
,"South Asian Center for Reintegration and Independent Research"
,"SRI International"
,"Streit Council"
,"Tax Foundation"
,"Texas Public Policy Foundation"
,"The Arctic Institute – Center for Circumpolar Security Studies"
,"The Century Foundation"
,"The Conference Board"
,"The Hampton Institute 已采"
,"The Heartland Institute"
,"The Lugar Center"
,"The Stimson Center"
,"The Washington Institute for Near East Policy"
,"Third Way"
,"Thomas B. Fordham Institute"
,"United States Institute of Peace"
,"Urban Institute"
,"Jewish Institute for National Security of America"
,"Joint Center for Political and Economic Studies"
,"Levy Economics Institute"
,"Lexington Institute"
,"Mackinac Center for Public Policy"
,"McKinsey Global Institute (MGI)"
,"National Bureau of Asian Research"
,"National Bureau of Economic Research (NBER)"
,"National Policy Institute"
,"Niskanen Center"
,"Pacific Research Institute"
,"Pew Research Center"
,"Pioneer Institute"
,"Policy Matters Ohio"
,"Potomac Institute for Policy Studies"
,"Progressive Policy Institute"
,"Prosperity Now (Corporation for Enterprise Development (CFED))"
,"Public Policy Institute of California"
,"RAND Corporation"
,"Reason Foundation"
,"Center for a New American Security (CNAS)"
,"Center for Advanced Defense Studies"
,"Center for American Progress (CAP)"
,"Center for Development and Strategy (CDS)"
,"Center for International Security and Cooperation"
,"Center for Media and Democracy (CMD)"
,"Center for Naval Analysis"
,"Center for Public Integrity (CPI)"
,"Center for Public Justice"
,"Center for Security Policy"
,"Center for Strategic and Budgetary Assessments (CSBA)"
,"Center for Strategic and International Studies (CSIS)"
,"Center for the National Interest"
,"Center for Transatlantic Relations"
,"Center on Budget and Policy Priorities (CBPP)"
,"Center on Global Interests"
,"Chicago Council on Global Affairs"
,"Committee for a Responsible Federal Budget (CRFB)"
,"Committee for Economic Development of The Conference Board（CED）"
,"Competitive Enterprise Institute (CEI)"
,"Constitution Project"
,"Council on Competitiveness"
,"CUTS International"
,"Demos"
,"Drum Major Institute for Public Policy (DMI)"
,"EastWest Institute"
,"Economic Opportunity Institute (EOI)"
,"Economic Policy Institute (EPI)"
,"Employment Policies Institute"
,"Federation for American Immigration Reform (FAIR)"
,"Foreign Policy Initiative"
,"Foreign Policy Research Institute"
,"Foundation for Defense of Democracies"
,"Commodity Futures Trading Commission(CFTC)"
,"Congress"
,"Congressional Budget Office"
,"Council of Economic Advisers"
,"Department of Commerce"
,"Department of Justice"
,"Department of State"
,"Department of the Interior"
,"Department of the Treasury"
,"Federal Deposit Insurance Corporation (FDIC)"
,"Federal Housing Finance Agency"
,"Federal Reserve Bank of Atlanta"
,"Federal Reserve Bank of Boston"
,"Federal Reserve Bank of Chicago"
,"Federal Reserve Bank of Cleveland"
,"Consumer Financial Protection Bureau (CFPB)"
,"Federal Reserve Bank of Dallas"
,"Foundation for Economic Education (FEE)"
,"Gatestone Institute"
,"German Marshall Fund of the United States"
,"Global Trade Watch"
,"GlobalSecurity"
,"Goldwater Institute"
,"Group of Thirty"
,"Heartland Institute"
,"Hispanic American Center for Economic Research (HACER)"
,"Hoover Institution"
,"Independence Institute (II)"
,"Independent Institute"
,"India, China & America Institute"
,"Institute for New Economic Thinking (INET)"
,"Institute for Science and International Security"
,"Institute for Women's Policy Research (IWPR)"
,"Institute on Taxation and Economic Policy"
,"Inter-American Dialogue"
,"Islands Society"
,"Israel Policy Forum"
,"J Street"
,"James A. Baker III Institute for Public Policy"
,"James Madison Institute"
,"Alliance for Financial Inclusion (AFI)"
,"African Development Bank (AfDB)"
,"Asian Development Bank (ADB)"
,"Asian Infrastructure Investment Bank (AIIB)"
,"Bank for International Settlements (BIS)"
,"Black Sea Trade and Development Bank (BSTDB)"
,"Council of Europe Development Bank (CEB)"
,"Eurasian Development Bank (EDB)"
,"European Bank for Reconstruction and Development (EBRD)"
,"European Free Trade Association (EFTA)"
,"Financial Action Task Force (FATF)"
,"Inter-American Development Bank (IADB)"
,"International Centre for Settlement of Investment Disputes (ICSID)"
,"International Development Association (IDA)"
,"International Monetary Fund (IMF)"
,"Islamic Development Bank (IDB)"
,"Multilateral Investment Guarantee Agency (MIGA)"
,"New Development Bank (NDB)"
,"OPEC Fund for International Development (OFID)"
,"Organisation for Economic Co-operation and Development (OECD)"
,"Organization of the Black Sea Economic Cooperation"
,"United Nations (UN)"
,"West African Development Bank (WADB)"
,"World Bank"
,"World Customs Organization (WCO)"
,"World Trade Organization (WTO)"
,"Z/Yen"
,"WebRoots Democracy"
,"Unlock Democracy"
,"United Nations Association – UK"
,"The Wilberforce Society"
,"The Constitution Society"
,"The Cobden Centre"
,"The Centre for Cross Border Studies"
,"Social Market Foundation"
,"Social Affairs Unit"
,"Conference Board of Canada"
,"Federal Reserve Bank of Kansas City"
,"Federal Reserve Bank of Minneapolis"
,"Federal Reserve Bank of New York"
,"Federal Reserve Bank of Philadelphia"
,"Federal Reserve Bank of San Francisco"
,"Federal Reserve Bank of St. Louis"
,"Financial Crimes Enforcement Network (FinCEN)"
,"Federal Trade Commission (FTC)"
,"Federal Reserve Board (FRB)"
,"Cascade Policy Institute"
,"General Accountability Office (GAO)"
,"Government Publishing Office (Catalog of U.S. Government Publications, CGP)"
,"National Credit Union Administration (NCUA)"
,"Office of the Comptroller of the Currency (OCC)"
,"International Finance Corporation (IFC)"
,"International Bank for Reconstruction and Development (IBRD)"
,"U.S. International Trade Commission (USITC)"
,"Small Business Administration"
,"Senate House"
,"Securities and Exchange Commission (SEC)"
,"Canadian International Council (CIC)"
,"Canadian Global Affairs Institute"
,"Canadian Centre for Policy Alternatives (CCPA)"
,"Canada West Foundation"
,"Caledon Institute of Social Policy"
,"C.D. Howe Institute"
,"Broadbent Institute"
,"Atlantic Provinces Economic Council"
,"Atlantic Institute for Market Studies (AIMS)"
,"Asia Pacific Foundation of Canada (APF Canada)"
,"Canadian Tax Foundation"
,"Centre for International Governance Innovation (CIGI)"
,"Australian Institute of International Affairs (AIIA)"
,"United States Studies Centre"
,"The Sydney Institute"
,"New Zealand Initiative"
,"Institute of Policy Studies"
,"Maxim Institute"
,"Centre for Strategic Studies New Zealand"
,"Oklahoma Policy Institute"
,"Fraser Institute"
,"The North-South Institute (NSI)"
,"The Institute for Research on Public Policy (IRPP)"
,"School of Public Policy and Governance (SPPG)"
,"Public Policy Forum (PPF)"
,"Montreal Economic Institute (MEI)"
,"Macdonald–Laurier Institute (MLI)"
,"International Institute for Sustainable Development (IISD)"
,"Frontier Centre for Public Policy (FCPP)"
,"Selsdon Group"
,"Scottish Constitutional Commission"
,"Science Policy Research Unit"
,"New Economics Foundation"
,"ResPublica"
,"Reform"
,"Progress"
,"Politeia"
,"Policy Studies Institute"
,"Policy Network"
,"Policy Exchange"
,"Next Century Foundation"
,"Jimmy Reid Foundation"
,"International Institute for Environment and Development"
,"Institute for Public Policy Research"
,"Center for Economic and Policy Research (CEPR)"
,"Institute for Democracy and Economic Affairs"
,"Fedesarrollo"
,"Hellenic Foundation for European and Foreign Policy"
,"Danish Institute for International Studies (DIIS)"
,"Copenhagen Institute for Futures Studies"
,"Centre for Political Studies (CEPOS)"
,"International Centre for Black Sea Studies"
,"Centre of Planning and Economic Research"
,"Center of Research for Development (CIDAC)"
,"Research Institute of the Finnish Economy (ETLA)"
,"S. Rajaratnam School of International Studies"
,"Singapore Institute of International Affairs (SIIA)"
,"World Economic Forum"
,"Amadeus Institute"
,"Economic and Social Research Institute (ESRI)"
,"Institute of International and European Affairs"
,"Think Tank for Action on Social Change (TASC)"
,"Horasis"
,"Centre for Development and Enterprise"
,"Geneva Centre for the Democratic Control of Armed Forces"
,"Free Market Foundation"
,"Millennium Institute"
,"Israel Democracy Institute"
,"Institute for National Security Studies (INSS)"
,"Avenir Suisse"
,"South African Institute of International Affairs"
,"Institute for Security Studies"
,"Jerusalem Center for Public Affairs"
,"Centre on Asia and Globalisation"
,"Turkish Economic and Social Studies Foundation"
,"GPoT Center"
,"Centre for Economics and Foreign Policy Studies (EDAM)"
,"Jerusalem Institute for Policy Research (JIPR)"
,"Reut Institute"
,"Stockholm International Peace Research Institute"
,"Institute for International Economic Studies (IIES)"
,"Captus"
,"Begin–Sadat Center for Strategic Studies"
,"Centre for Fair Political Analysis"
,"Foraus"
,"Association for Liberal Thinking (ALT)"
,"Center for European Renewal"
,"Finnish Institute of International Affairs (FIIA)"
,"Real Instituto Elcano"
,"Fundación Alternativas"
,"Barcelona Centre for International Affairs"
,"Japan Center for Economic Research (JCER)"
,"The Casimir Pulaski Foundation"
,"Sobieski Institute"
,"Kosciuszko Institute"
,"Institute of International Affairs"
,"Netherlands Bureau for Economic Policy Analysis (CPB)"
,"Netherlands Institute for Multiparty Democracy"
,"Edmund Burke Foundation"
,"Clingendael, Netherlands Institute of International Relations"
,"Trinità dei Monti"
,"demosEUROPA - Centre for European Strategy"
,"Centre for Eastern Studies"
,"Center for Social and Economic Research (CASE)"
,"Adam Smith Centre"
,"Friends of Europe"
,"European Policy Centre (EPC)"
,"European Centre for International Political Economy (ECIPE)"
,"Egmont Group of Financial Intelligence Units"
,"EGMONT – The Royal Institute for International Relations"
,"Centre for European Policy Studies (CEPS)"
,"Bruegel"
,"Centre d'Etudes Prospectives et d'Informations Internationales (CEPII)"
,"French Institute of International Relations（IFRI)"
,"Jacques Delors Institute"
,"Institut Montaigne"
,"Gracques"
,"Institut des Relations Internationales et Strategiques (IRIS)"
,"European Laboratory of Political Anticipation (LEAP2020)"
,"Center for Economic and Social Development (CESD)"
,"International Growth Centre (IGC)"
,"Kenya Institute for Public Policy Research and Analysis (KIPPRA)"
,"African Economic Research Consortium (AERC)"
,"Centro de Estudio de la Realidad Economica y Social (CERES)"
,"Economics Institute"
,"Institute for Public Affairs"
,"Federation of Euro-Asian Stock Exchanges (FEAS)"
,"Valdai Discussion Club"
,"Moscow State Institute of International Relations (MGIMO)"
,"Institute of World Economy and International Relations (IMEMO RAS)"
,"Center for Fiscal Policy (CFP)"
,"Center for Economic and Financial Research (CEFIR)"
,"Carnegie Moscow Center"
,"Analytical Center for the Government of the Russian Federation"
,"India Council for Research on International Economic Relations(ICRIER)"
,"International Centre for Policy Studies"
,"Centro Brasileiro de Relacoes Internacionais (CEBRI)"
,"Fundacao Armando Alvares Penteado (FAAP)"
,"Fundacao Getulio Vargas (FGV)"
,"Asan Institute for Policy Studies"
,"Korea Development Institute (KDI)"
,"Korea Institute for International Economic Policy (KIEP)"
,"New Economic School – Georgia"
,"Sejong Institute"
,"Bangladesh Institute of Law and International Affairs (BILIA)"
,"Centre for Policy Dialogue (CPD)"
,"African Centre for Development and Strategic Studies"
,"National Institute of Policy and Strategic Studies"
,"Nigerian Institute of International Affairs"
,"Bangladesh Institute of Development Studies (BIDS)"
,"Institute of World Economics and Politics (IWEP)"
,"Organization for Social Science Research in Eastern and Southern Africa (OSSREA)"
,"Albanian Institute for International Studies (AIIS)"
,"University of Asia and the Pacific"
,"Centro de Estudios Publicos (CEP)"
,"IMANI Center for Policy and Education"
,"Libertad y Desarrollo (LyD)"
,"Economic Research Institute for ASEAN and East Asia (ERIA)"
,"Centre for Strategic and International Studies"
,"LIRNEasia"
,"Institute of Regional Studies"
,"Applied Economics Research Centre"
,"Consejo Argentino para las Relaciones Internacionales (CARI)"
,"Centro de Implementacion de Politicas Publicas para la Equidad y el Crecimiento (CIPPEC)"
,"Egyptian Center for Economic Studies (ECES)"
,"Austrian Institute of Economic Research (WIFO)"
,"Vienna Institute for International Economic Studies (WIIW)"
,"Georgian Foundation for Strategic and International Studies"
,"Razumkov Centre"
,"Strategic Foresight Group"
,"Chennai Centre for China Studies"
,"Pakistan Institute of Development Economics"
,"Centre for Public Policy Research"
,"Centre for Civil Society"
,"Association for Democratic Reforms"
,"Islamabad Policy Research Institute"
,"Pakistan Institute of International Affairs"
,"Itinera Institute"
,"Lakshman Kadirgamar Institute of International Relations and Strategic Studies"
,"Institute of Applied Economic Research"
,"Institute for Social and Economic Analyses (ISEA)"
,"Social Policy and Development Centre"
,"Sustainable Development Policy Institute"
,"AARP Public Policy Institute"
,"Adam Smith Foundation"
,"Arkansas Policy Foundation"
,"Chicago Community Trust"
,"Citizens Policy Foundation"
,"Council On Foundation"
,"Economic Policy Institute"
,"Ford Foundation"
,"Foundation for Rational Economics and Education"
,"Future of American Democracy Foundation"
,"Georgia Public Policy Foundation"
,"Horowitz Foundation For Social Policy"
,"International Republican Institute"
,"John William Pope Foundation"
,"Kettering Foundation"
,"Land Policy Institute"
,"MacArthur Foundation"
,"NASW Foundation"
,"Netherland-America Foundation"
,"New York Community Trust"
,"OpenGov Foundation"
,"Participatory Politics Foundation"
,"Randolph Foundation"
,"Russell Sage Foundation"
,"Scaife Foundations"
,"Silicon Valley Community Foundation"
,"Smith Richardson Foundation"
,"Spark Policy Institute"
,"Stanley Foundation"
,"Sunlight Foundation"
,"The Boston Foundation"
,"The Heritage Foundation"
,"The U.S.- China Policy Foundation"
,"Tulsa Community Foundation"
,"United Nations Foundation"
,"Tellus Institute"
,"World Affairs Councils of America"
,"Oregon Center for Public Policy"
,"Pacific Forum International"
,"New Democrat Network"
,"New America Foundation"
,"Philadelphia Society"
,"Ludwig von Mises Institute"
,"McCain Institute"
,"Manhattan Institute for Policy Research (MI)"
,"Migration Policy Institute"
,"Milken Institute"
,"Middle East Forum"
,"John S. Watson Institute for Public Policy"
,"Institute for Policy Studies (IPS)"
,"Jamestown Foundation"
,"Hudson Institute"
,"Cato Institute"
,"Center for Governmental Research (CGR)"
,"City Mayors Foundation"
,"Brand EU"
,"Common Weal"
,"Constitution Unit"
,"Stockholm Network"
,"Henry Jackson Society"
,"Vivekananda International Foundation"
,"Ratio Institute"
,"Institut Choiseul for International Politics and Geoeconomics"
,"Institute for US and Canadian Studies"
,"Institute for International Political Studies (ISPI)"
,"International Strategic Research Organization"
,"Financial Conduct Authority"
,"Concord Coalition"
,"Peterson Institute for International Economics (PIIE)"
,"Africa Center for Strategic Studies"
,"Asia Society Policy Institute（ASPI）"
,"Aspen Institute"
,"Arctic Institute"
,"Center for Data Innovation"
,"Center for European Policy Analysis"
,"Center for the National Interest (CFTNI), FKA Nixon Center"
,"Center for National Policy (CNP)"
,"Congressional Research Service"
,"Council on Foreign Relations (CFR)"
,"Demand Progress Education Fund"
,"Earth institute"
,"Global Trade Analysis Project （GTAP)"
,"Institute for Defense Analysis"
,"Institute for Religion and Democracy (IRD)"
,"Information Technology and Innovative Foundation"
,"Levy Institute"
,"Lugar Center"
,"Library of Congress"
,"Mercatus Center"
,"New York Law Journal"
,"Open Markets Institute"
,"Open Society Foundations (OSF), FKA Open Society Institute"
,"Pacific Council on International Policy"
,"Pamplin College of Business"
,"Project for the Study of the 21st Century (PS21)"
,"Public Citizen"
,"Resources for the Future"
,"Stimson Center"
,"The Peter G.Peterson Foundation"
,"US-China Economic and Security Review Commission (USCC)"
,"Washington Center for Equitable Growth （WEGC）"
,"Williams Mullen"
,"Wilson Center, FKA Woodrow Wilson International Center for Scholars"
,"Woodrow Wilson International Center for Scholars"
,"Amnesty International (AI)"
,"Centre for European Reform (CER)"
,"Centre for Progressive Capitalism"
,"Cesran International"
,"Development Initiatives"
,"European Leadership Network"
,"Legatum Institute"
,"Overseas Development Institute (ODI)"
,"Oxford Council on Good Governance (OCGG)"
,"Royal United Services Institute (RUSI)"
,"Canada 2020"
,"Canadian Taxpayers Federation"
,"Eco-Fiscal Commission"
,"Global Network for Africa’s Prosperity (GNAP)"
,"Mackenzie Institute"
,"Mowat Center"
,"Pembina Institute"
,"TRT World Research Centre"
,"Canon Institute for Global Studies"
,"Institute of Developing Economies, Japan External Trade Organization (IDEJETRO)"
,"Institute of Energy Economics, Japan (IEEJ)"
,"Institute of International and Strategic Studies (IISS)"
,"Institute for International Policy Studies (IIPS)"
,"Japan Policy Research Institute (PRI)"
,"Sasakawa Peace Foundation"
,"Tokyo Foundation"
,"Bertelsmann Foundation"
,"Centre for Global Cooperation Research"
,"Deutsches Institut für Wirtschaftsforschung (DIW)"
,"Duesseldorf Center for Competition Economics (DICE)"
,"Ecologic Institute"
,"European Stability Initiative"
,"Jacques Delors Institut"
,"German Development Institute (DIE)"
,"Institute for Advanced Sustainability Studies"
,"Koerber Foundation"
,"Potsdam Institute for Climate Impact Research"
,"Transparency International (TI)"
,"Australia China Relations Institute (ACRI)"
,"Institute for Economics and Peace (IEP)"
,"Institute for Regional Security"
,"Institute for Policy Analysis of Conflict"
,"Lowy Institute for International Policy"
,"Brookings Institution"
,"Carnegie Endowment for International Peace"
,"Centre for the Study of Developing Societies (CSDS)"
,"Development Alternatives (DA)"
,"Hindu Centre for Politics and Public Policy"
,"Indian Council of World Affairs (ICWA)"
,"Institute of Economic Growth (IEG)"
,"Integrated Research and Action for Development (IRADe)"
,"Alternate Solutions Institute"
,"Area Study Centre for Far East and Southeast Asia (FESEA)"
,"Center for Research on Economic and Social Transformation (CREST)"
,"Policy Research Institute of Market Economy"
,"Adviser on Strategic Foresight"
,"European Organisation for Security"
,"Foundation for European Progressive Studies (FEPS)"
,"German Marshall Fund"
,"International Crisis Group (ICG)"
,"Lisbon Council for Economic Competitiveness and Social Renewal"
,"Security and Defence Agenda (SDA)"
,"Arava Institute"
,"Avinoam Bar, FKA Jewish People Policy Institute (JPPPI)"
,"International Institute for Counter-Terrorism (ICT)"
,"Israel Center for Social and Economic Progress (ICSEP)"
,"Jerusalem Institute for Market Studies"
,"Kohelet Policy Forum"
,"Maurice Falk Institute for Economic Research"
,"Moshe Dayan Center for Middle Eastern and African Studies"
,"Casimir Pulaski Foundation (CPF)"
,"Center for Economic Analysis (CenEA)"
,"Center for International Relations (CIR)"
,"Institute of Economics"
,"Polish Institute of International Affairs (PISM)"
,"WISE Europa"
,"Carnegie Endowment for International Peace Moscow Center"
,"Centre for Independent Social Research"
,"Economic Expert Group (EEG)"
,"Independent Institute for Social Policy (IISP)"
,"Institute for Applied Economic Studies"
,"Institute for Urban Economics (IUE)"
,"Gaidar Institute for Economic Policy (IEP)"
,"Primakov Institute of World Economy and International Relations (IMEMO)"
,"Russian International Affairs Council (RIAC)"
,"St.Petersburg Center for Humanities and Political Studies"
,"Centre d'Etudes et de Recherches Internationales (CERI)"
,"European Union Institute for Security Studies (EUISS)"
,"Fondation Robert Schuman"
,"Fondation pour la Recherche Strategique (FRS)"
,"Fondation pour l'Innovation Politique (Fondapol)"
,"Institut de Recherche Strategique de l'Ecole Militaire"
,"Institute for Research in Economic and Fiscal Issues (IREF)"
,"Institut Molinari"
,"Notre Europe Jacques Delors Institut"
,"Action Institute"
,"Centro Studi Internazionali (Ce.S.I.)"
,"Fondazione Eni Enrico Mattei (FEEM)"
,"International Center for Climate Governance (ICCG)"
,"Istituto Affari Internazionali (IAI)"
,"Istituto Bruno Leoni (IBL)"
,"Torino World Affairs Institute"
,"European Centre for Development Policy Management (ECDPM)"
,"Center for Strategic Research (SAM)"
,"Istanbul Policy Center"
,"Institute of Defence and Strategic Studies (IDSS)"
,"Institute of Southeast Asian Studies (ISEAS)"
,"Asia Competitiveness Institute (ACI)"
,"Political Risks Assessment Group"
,"Ecologic Foundation"
,"New Zealand Institute of International Affairs (NZIIA)"
,"Centro Brasileiro de Análise e Planejamento (CEBRAP)"
,"Korea Energy Economics Institute (KEEI)"
,"African Centre for the Constructive Resolution of Disputes (ACCORD)"
,"EuroMeSCo"
,"Fundacion para el Analisis y los Estudios Sociales (FAES)"
,"European Centre of Excellence for Countering Hybrid Threats (Hybrid CoE)"
,"Centro de Investigacion y Docencia Economicas (CIDE)"
,"Fundacion Idea"
,"Al-Ahr am Center for Political and Strategic Studies (ACPSS)"
,"Innovations in Politics Institute"
,"Corporación de Estudios para Latinoamérica (CIEPLAN)"
,"NHH Norwegian School of Economics"
,"Issam Fares Institute for Public Policy and International Affairs (IFI)"
,"Kansas Policy Institute"
,"Project 2049 Institute"
,"Claremont Institute"
,"Kuhn Foundation"
,"Nigerian Economic Summit Group"
,"Eudoxa"
,"Timbro"
,"McGuinness Institute"
,"Israel Council on Foreign Relations"
,"Future Italy"
,"European University Institute"
,"Centre for Economic and Social Inclusion"
,"The Takshashila Institution"
,"Observer Research Foundation (ORF)"
,"Institute of Strategic Studies Islamabad"
,"Jerusalem Institute for Market Studies "
,"Asian Development Bank Institute (ADBI)"
,"A.T. Kearney Global Business Policy Council (GBPC)"
,"Accenture Institue for High Performance"
,"Bloomberg BNA"
,"Boston Consulting Group (BCG)"
,"Center for International Development (CID)"
,"Cohen Group"
,"Control Risks Group"
,"E.Y., FKA Ernst & Young"
,"GovLab, Deloitte"
,"IBM Institute ofr Business Value"
,"Kissinger Associates"
,"Kreller Business Information Group"
,"Kroll Associates"
,"Medley Global Advisors"
,"Mossavar-Rahmani Center for Business and Government, Harvard University"
,"National Center for Public Policy Research (NCPPR)"
,"National Venture Capital Association"
,"Oxford Analytica"
,"PricewaterhouseCoopers (PwC)"
,"Roubini Global Economics (RGE)"
,"Smith Brandon International Inc."
,"Yale Center for the Study of Globalization"
,"Aegis"
,"Deloitte Touche Tohmatsu"
,"Economist Intelligence Unit (EIU)"
,"Frontier Horizons"
,"IDEAS"
,"Institute for Development Studies"
,"Tax payers Alliance"
,"Center for International Policy Studies"
,"China Institute"
,"Facultad Latinoamericana de Ciencias Sociales (FLACSO)"
,"Asia Pacific Initiative"
,"Japan Institute for International Development"
,"Institute for Ecological Economy Research (IÖW)"
,"Institute of Labor Economics (IZA)"
,"Macroeconomic Policy Institute (IMK)"
,"Centre for Internet and Society (CIS)"
,"Delhi Policy Group (DPG)"
,"Foundation for Democratic Reforms"
,"Gateway House: Indian Council on Global Relations"
,"India Foundation"
,"Indira Gandhi Institute of Development Research (IGIDR)"
,"Institute for Public Enterprise"
,"National Council of Applied Economic Research (NCAER)"
,"Van Leer Jerusalem Institute (VLJI)"
,"Fundacja Forum Obywatelskiego Rozwoju (FOR)"
,"Jagiellonian Club's Centre of Analysis"
,"National Institute for Strategic Studies"
,"Institute of Economy of the Russian Academy of Sciences (EDIRC)"
,"Institute for Sustainable Development and International Relations"
,"KPMG"
,"Center for Turkey's Economic and Strategic Studies"
,"Economic Policy Research Foundation of Turkey"
,"East Asian Institute (EAI)"
,"Fundación de Investigaciones Económicas Latinoamericanas (FIEL)"
,"Latin American Security and Defence Network (RESDAL)"
,"BRICS Policy Center"
,"Botswana Institute for Development Policy Analysis (BIDPA)"
,"Ateneo Center for Economic Research and Development (ACERD)"
,"Initiatives for International Dialogue (IID)"
,"Institute for Strategic and Development Studies (ISDS)"
,"Korea Economic Research Institute"
,"Samsung Economic Research Institute (SERI)"
,"Institute of Policy Studies of Sri Lanka (IPS)"
,"Centre for Poverty Analysis (CEPA)"
,"Institute for National Security Studies"
,"Institute of National Capacity Studies (INCS)"
,"Vietnam Institute for American Studies"
,"Scottish Global Forum"
,"Center for Development and Strategy"
) GROUP BY website;
