UPDATE think_tank_website set region = "波兰", type = "智库", url = "http://smith.pl/" WHERE website = "Adam Smith Centre";
UPDATE think_tank_website set region = "比利时", type = "智库", url = "https://foresight.ca" WHERE website = "Adviser on Strategic Foresight";
UPDATE think_tank_website set region = "尼日利亚", type = "智库", url = "https://africacenter.org/" WHERE website = "African Centre for Development and Strategic Studies";
UPDATE think_tank_website set region = "南非", type = "智库", url = "https://www.accord.org.za" WHERE website = "African Centre for the Constructive Resolution of Disputes (ACCORD)";
UPDATE think_tank_website set region = "阿尔巴尼亚", type = "智库", url = "http://www.aiis-albania.org/" WHERE website = "Albanian Institute for International Studies (AIIS)";
UPDATE think_tank_website set region = "巴基斯坦", type = "智库", url = "https://asinstitute.org" WHERE website = "Alternate Solutions Institute";
UPDATE think_tank_website set region = "摩洛哥", type = "智库", url = "https://www.amadeusonline.org/" WHERE website = "Amadeus Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://americanactionnetwork.org/" WHERE website = "American Action Network";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.theacru.org/" WHERE website = "American Civil Rights Union";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.us-iran.org/" WHERE website = "American Iranian Council";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://ascfusa.org/" WHERE website = "American Security Council Foundation";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.amnesty.org/en" WHERE website = "Amnesty International (AI)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.analysisgroup.com/" WHERE website = "Analysis Group";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "https://arava.org" WHERE website = "Arava Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.thearcticinstitute.org/" WHERE website = "Arctic Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://asiasociety.org/policy-institute" WHERE website = "Asia Society Policy Institute（ASPI）";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://adrindia.org/" WHERE website = "Association for Democratic Reforms";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "https://www.australiachinarelations.org/" WHERE website = "Australia China Relations Institute (ACRI)";
UPDATE think_tank_website set region = "孟加拉国", type = "智库", url = "http://www.biliabd.org/" WHERE website = "Bangladesh Institute of Law and International Affairs (BILIA)";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "https://besacenter.org/" WHERE website = "Begin–Sadat Center for Strategic Studies";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.berggruen.org/" WHERE website = "Berggruen Institute";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.bfna.org" WHERE website = "Bertelsmann Foundation";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.brugesgroup.com/" WHERE website = "Bruges Group";
UPDATE think_tank_website set region = "加拿大", type = "智库", url = "http://www.ctf.ca/" WHERE website = "Canadian Tax Foundation";
UPDATE think_tank_website set region = "加拿大", type = "智库", url = "https://www.taxpayer.com" WHERE website = "Canadian Taxpayers Federation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.carnegiecouncil.org/" WHERE website = "Carnegie Council for Ethics in International Affairs";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://carnegieendowment.org" WHERE website = "Carnegie Endowment for International Peace (CEIP)";
UPDATE think_tank_website set region = "俄罗斯", type = "智库", url = "https://carnegie.ru/?lang=en" WHERE website = "Carnegie Endowment for International Peace Moscow Center";
UPDATE think_tank_website set region = "俄罗斯", type = "智库", url = "http://carnegie.ru/?lang=en" WHERE website = "Carnegie Moscow Center";
UPDATE think_tank_website set region = "波兰", type = "智库", url = "https://pulaski.pl/en/about-cpf" WHERE website = "Casimir Pulaski Foundation (CPF)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.cnas.org" WHERE website = "Center for a New American Security (CNAS)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://c4ads.org/" WHERE website = "Center for Advanced Defense Studies";
UPDATE think_tank_website set region = "荷兰", type = "智库", url = "N/A" WHERE website = "Center for European Renewal";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://freedomandprosperity.org/" WHERE website = "Center for Freedom and Prosperity (CFP)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.cgr.org/" WHERE website = "Center for Governmental Research (CGR)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.cis.org/" WHERE website = "Center for Immigration Studies";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://cisac.fsi.stanford.edu/" WHERE website = "Center for International Security and Cooperation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://prwatch.org/" WHERE website = "Center for Media and Democracy (CMD)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.cna.org/centers/cna/" WHERE website = "Center for Naval Analysis";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.cpjustice.org/public/page/content/homepage" WHERE website = "Center for Public Justice";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.centerforsecuritypolicy.org/" WHERE website = "Center for Security Policy";
UPDATE think_tank_website set region = "土耳其", type = "智库", url = "sam.gov.tr" WHERE website = "Center for Strategic Research (SAM)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://cftni.org/" WHERE website = "Center for the National Interest";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://transatlanticrelations.org/" WHERE website = "Center for Transatlantic Relations";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://www.ccsindia.org/" WHERE website = "Centre for Civil Society";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.cer.eu" WHERE website = "Centre for European Reform (CER)";
UPDATE think_tank_website set region = "加拿大", type = "智库", url = "http://cigionline.org/" WHERE website = "Centre for International Governance Innovation (CIGI)";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "https://cpd.org.au/" WHERE website = "Centre for Policy Development";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://www.cppr.in/" WHERE website = "Centre for Public Policy Research";
UPDATE think_tank_website set region = "巴西", type = "智库", url = "d3nv1jy4u7zmsc.cloudfront.net/" WHERE website = "Centro Brasileiro de Análise e Planejamento (CEBRAP)";
UPDATE think_tank_website set region = "巴西", type = "智库", url = "http://www.cebri.org/" WHERE website = "Centro Brasileiro de Relacoes Internacionais (CEBRI)";
UPDATE think_tank_website set region = "乌拉圭", type = "智库", url = "http://www.ceres-uy.org/" WHERE website = "Centro de Estudio de la Realidad Economica y Social (CERES)";
UPDATE think_tank_website set region = "阿根廷", type = "智库", url = "https://www.cippec.org/" WHERE website = "Centro de Implementacion de Politicas Publicas para la Equidad y el Crecimiento (CIPPEC)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://cesran.org" WHERE website = "Cesran International";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.claremont.org/" WHERE website = "Claremont Institute";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "http://www.ceda.com.au/" WHERE website = "Committee for Economic Development of Australia (CEDA)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://www.allofusfirst.org/" WHERE website = "Common Weal";
UPDATE think_tank_website set region = "美国", type = "美政府网站", url = "https://www.congress.gov/" WHERE website = "Congress";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.ucl.ac.uk/constitution-unit" WHERE website = "Constitution Unit";
UPDATE think_tank_website set region = "智利", type = "智库", url = "www.cieplan.org" WHERE website = "Corporación de Estudios para Latinoamérica (CIEPLAN)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.cuts-international.org/" WHERE website = "CUTS International";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.data.gov" WHERE website = "data.gov";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://demandprogresseducationfund.org/#/" WHERE website = "Demand Progress Education Fund";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.demos.org/" WHERE website = "Demos";
UPDATE think_tank_website set region = "波兰", type = "智库", url = "http://www.demoseuropa.eu/" WHERE website = "demosEUROPA - Centre for European Strategy";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.diw.de" WHERE website = "Deutsches Institut für Wirtschaftsforschung (DIW)";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "https://devpolicy.crawford.anu.edu.au/" WHERE website = "Development Policy Centre";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "http://www.eaber.org/" WHERE website = "East Asian Bureau of Economic Research (EABER)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.eastwest.ngo/" WHERE website = "EastWest Institute";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.ecologic.eu" WHERE website = "Ecologic Institute";
UPDATE think_tank_website set region = "俄罗斯", type = "智库", url = "https://www.devex.com/organizations/economic-expert-group-eeg-47621" WHERE website = "Economic Expert Group (EEG)";
UPDATE think_tank_website set region = "荷兰", type = "智库", url = "N/A" WHERE website = "Edmund Burke Foundation";
UPDATE think_tank_website set region = "瑞典", type = "智库", url = "http://www.archive.org/" WHERE website = "Eudoxa";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.ecfr.eu" WHERE website = "European Council on Foreign Relations (ECFR)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.europeanleadershipnetwork.org/" WHERE website = "European Leadership Network";
UPDATE think_tank_website set region = "比利时", type = "智库", url = "www.eos-eu.com" WHERE website = "European Organisation for Security";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.esiweb.org" WHERE website = "European Stability Initiative";
UPDATE think_tank_website set region = "法国", type = "智库", url = "https://www.iss.europa.eu" WHERE website = "European Union Institute for Security Studies (EUISS)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.everycrsreport.com" WHERE website = "everycrsreport.com";
UPDATE think_tank_website set region = "克利夫兰", type = "美政府网站", url = "https://www.clevelandfed.org/" WHERE website = "federal Reserve Bank of Cleveland";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.fairus.org/" WHERE website = "Federation for American Immigration Reform (FAIR)";
UPDATE think_tank_website set region = "法国", type = "智库", url = "www.fondapol.org" WHERE website = "Fondation pour l'Innovation Politique (Fondapol)";
UPDATE think_tank_website set region = "法国", type = "智库", url = "https://www.robert-schuman.eu/en" WHERE website = "Fondation Robert Schuman";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.fdd.org/" WHERE website = "Foundation for Defense of Democracies";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.fes.de/" WHERE website = "Friedrich Ebert Foundation";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://fnst.org/" WHERE website = "Friedrich Naumann Foundation";
UPDATE think_tank_website set region = "巴西", type = "智库", url = "http://www.faap.br/" WHERE website = "Fundacao Armando Alvares Penteado (FAAP)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.gatestoneinstitute.org/" WHERE website = "Gatestone Institute";
UPDATE think_tank_website set region = "瑞士", type = "智库", url = "http://www.dcaf.ch/" WHERE website = "Geneva Centre for the Democratic Control of Armed Forces";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.swp-berlin.org/en/" WHERE website = "German Institute for International and Security Affairs (SWP)";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.giga-hamburg.de/" WHERE website = "German Institute of Global and Area Studies";
UPDATE think_tank_website set region = "比利时", type = "智库", url = "www.gmfus.org" WHERE website = "German Marshall Fund";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.gmfus.org/" WHERE website = "German Marshall Fund of the United States";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://goldwaterinstitute.org/" WHERE website = "Goldwater Institute";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.green-alliance.org.uk/" WHERE website = "Green Alliance";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.hansardsociety.org.uk/" WHERE website = "Hansard Society";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.heartland.org/" WHERE website = "Heartland Institute";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://henryjacksonsociety.org/" WHERE website = "Henry Jackson Society";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://thehinducentre.com" WHERE website = "Hindu Centre for Politics and Public Policy";
UPDATE think_tank_website set region = "瑞士", type = "智库", url = "https://horasis.org/" WHERE website = "Horasis";
UPDATE think_tank_website set region = "加纳", type = "智库", url = "https://imaniafrica.org/" WHERE website = "IMANI Center for Policy and Education";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.itif.org" WHERE website = "Information Technology and Innovative Foundation";
UPDATE think_tank_website set region = "奥地利", type = "智库", url = "https://www.innovationinpolitics.eu" WHERE website = "Innovations in Politics Institute";
UPDATE think_tank_website set region = "法国", type = "智库", url = "https://www.irsem.fr" WHERE website = "Institut de Recherche Strategique de l'Ecole Militaire";
UPDATE think_tank_website set region = "法国", type = "智库", url = "http://www.iris-france.org" WHERE website = "Institut des Relations Internationales et Strategiques (IRIS)";
UPDATE think_tank_website set region = "法国", type = "智库", url = "https://www.institutmolinari.org" WHERE website = "Institut Molinari";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.iass-potsdam.de/en" WHERE website = "Institute for Advanced Sustainability Studies";
UPDATE think_tank_website set region = "俄罗斯", type = "智库", url = "https://www.laedc.org/research-analysis" WHERE website = "Institute for Applied Economic Studies";
UPDATE think_tank_website set region = "美国", type = "智库", url = "www.idsa-india.org/ " WHERE website = "Institute for Defense Analysis";
UPDATE think_tank_website set region = "马来西亚", type = "智库", url = "http://www.ideas.org.my/" WHERE website = "Institute for Democracy and Economic Affairs";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.jpr.org.uk/" WHERE website = "Institute for Jewish Policy Research";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "http://www.understandingconflict.org/en.html" WHERE website = "Institute for Policy Analysis of Conflict";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://ips-dc.org/" WHERE website = "Institute for Policy Studies (IPS)";
UPDATE think_tank_website set region = "斯洛伐克", type = "美政府网站", url = "http://www.ivo.sk/106/en/home" WHERE website = "Institute for Public Affairs";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://theird.org" WHERE website = "Institute for Religion and Democracy (IRD)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.isis-online.org/" WHERE website = "Institute for Science and International Security";
UPDATE think_tank_website set region = "南非", type = "智库", url = "https://issafrica.org/" WHERE website = "Institute for Security Studies";
UPDATE think_tank_website set region = "捷克", type = "智库", url = "N/A" WHERE website = "Institute for Social and Economic Analyses (ISEA)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.iwpr.org/" WHERE website = "Institute for Women's Policy Research (IWPR)";
UPDATE think_tank_website set region = "俄罗斯", type = "智库", url = "https://www.imemo.ru/en/" WHERE website = "Institute of World Economy and International Relations (IMEMO RAS)";
UPDATE think_tank_website set region = "意大利", type = "智库", url = "https://www.greengrowthknowledge.org/" WHERE website = "International Center for Climate Governance (ICCG)";
UPDATE think_tank_website set region = "希腊", type = "智库", url = "http://www.icbss.org/" WHERE website = "International Centre for Black Sea Studies";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "https://www.ict.org.il" WHERE website = "International Institute for Counter-Terrorism (ICT)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.iied.org/" WHERE website = "International Institute for Environment and Development";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://islandssociety.org/" WHERE website = "Islands Society";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "www.icsep.org.il" WHERE website = "Israel Center for Social and Economic Progress (ICSEP)";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "http://www.israelcfr.com/" WHERE website = "Israel Council on Foreign Relations";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://israelpolicyforum.org/" WHERE website = "Israel Policy Forum";
UPDATE think_tank_website set region = "黎巴嫩", type = "智库", url = "http://website.aub.edu.lb/ifi/Pages/index.aspx" WHERE website = "Issam Fares Institute for Public Policy and International Affairs (IFI)";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://jamestown.org/" WHERE website = "Jamestown Foundation";
UPDATE think_tank_website set region = "日本", type = "智库", url = "https://www.jpri.org/" WHERE website = "Japan Policy Research Institute (PRI)";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "http://www.jcpa.org/" WHERE website = "Jerusalem Center for Public Affairs";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.jinsa.org/" WHERE website = "Jewish Institute for National Security of America";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://reidfoundation.org/" WHERE website = "Jimmy Reid Foundation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.tesu.edu/watson/institute/index" WHERE website = "John S. Watson Institute for Public Policy";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.koerber-stiftung.de/en" WHERE website = "Koerber Foundation";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.kas.de/" WHERE website = "Konrad Adenauer Foundation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.closertotruth.com" WHERE website = "Kuhn Foundation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "www.levyinstitute.org" WHERE website = "Levy Institute";
UPDATE think_tank_website set region = "斯里兰卡", type = "智库", url = "https://lirneasia.net/" WHERE website = "LIRNEasia";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "https://www.lowyinstitute.org" WHERE website = "Lowy Institute for International Policy";
UPDATE think_tank_website set region = "美国", type = "智库", url = "www.thelugarcenter.org/" WHERE website = "Lugar Center";
UPDATE think_tank_website set region = "加拿大", type = "智库", url = "https://www.mckenzieinstitute.org" WHERE website = "Mackenzie Institute";
UPDATE think_tank_website set region = "新西兰", type = "智库", url = "http://www.mcguinnessinstitute.org/" WHERE website = "McGuinness Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.meforum.org/" WHERE website = "Middle East Forum";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "https://dayan.org" WHERE website = "Moshe Dayan Center for Middle Eastern and African Studies";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.ndn.org/" WHERE website = "New Democrat Network";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://nextcenturyfoundation.org/" WHERE website = "Next Century Foundation";
UPDATE think_tank_website set region = "尼日利亚", type = "智库", url = "https://nesgroup.org/" WHERE website = "Nigerian Economic Summit Group";
UPDATE think_tank_website set region = "尼日利亚", type = "智库", url = "https://www.niia.gov.ng/" WHERE website = "Nigerian Institute of International Affairs";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://niskanencenter.org/" WHERE website = "Niskanen Center";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.opensocietyfoundations.org/" WHERE website = "Open Society Foundations (OSF), FKA Open Society Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://pamplin.vt.edu/" WHERE website = "Pamplin College of Business";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.hsfk.de/?L=1" WHERE website = "Peace Research Institute Frankfurt";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://phillysoc.org/" WHERE website = "Philadelphia Society";
UPDATE think_tank_website set region = "新加坡", type = "智库", url = "https://www.prsgroup.com" WHERE website = "Political Risks Assessment Group";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.pik-potsdam.de" WHERE website = "Potsdam Institute for Climate Impact Research";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://project2049.net/" WHERE website = "Project 2049 Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.citizen.org" WHERE website = "Public Citizen";
UPDATE think_tank_website set region = "乌克兰", type = "智库", url = "http://razumkov.org.ua/en/" WHERE website = "Razumkov Centre";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://reason.org/" WHERE website = "Reason Foundation";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.rff.org" WHERE website = "Resources for the Future";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://www.respublica.org.uk/" WHERE website = "ResPublica";
UPDATE think_tank_website set region = "以色列", type = "智库", url = "https://reutgroup.org/en/" WHERE website = "Reut Institute";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.riponsociety.org/" WHERE website = "Ripon Society";
UPDATE think_tank_website set region = "德国", type = "智库", url = "https://www.rosalux.de/" WHERE website = "Rosa Luxemburg Foundation";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://rusi.org" WHERE website = "Royal United Services Institute (RUSI)";
UPDATE think_tank_website set region = "日本", type = "智库", url = "https://spfusa.org" WHERE website = "Sasakawa Peace Foundation";
UPDATE think_tank_website set region = "加拿大", type = "智库", url = "https://publicpolicy.utoronto.ca/" WHERE website = "School of Public Policy and Governance (SPPG)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://www.constitutionalcommission.org/" WHERE website = "Scottish Constitutional Commission";
UPDATE think_tank_website set region = "韩国", type = "智库", url = "http://www.sejong.org/eng/" WHERE website = "Sejong Institute";
UPDATE think_tank_website set region = "波兰", type = "智库", url = "http://sobieski.org.pl/" WHERE website = "Sobieski Institute";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://www.socialaffairsunit.org.uk/" WHERE website = "Social Affairs Unit";
UPDATE think_tank_website set region = "南非", type = "智库", url = "https://saiia.org.za/" WHERE website = "South African Institute of International Affairs";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.sacrir.org/" WHERE website = "South Asian Center for Reintegration and Independent Research";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.stimson.org/" WHERE website = "Stimson Center";
UPDATE think_tank_website set region = "瑞典", type = "智库", url = "https://www.sipri.org/" WHERE website = "Stockholm International Peace Research Institute";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://www.stockholm-network.org/" WHERE website = "Stockholm Network";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "http://sdsc.bellschool.anu.edu.au/" WHERE website = "Strategic and Defence Studies Centre (SDSC)";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://strategicforesight.com/" WHERE website = "Strategic Foresight Group";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://streitcouncil.org/" WHERE website = "Streit Council";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.thearcticinstitute.org/" WHERE website = "The Arctic Institute – Center for Circumpolar Security Studies";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://www.consoc.org.uk/" WHERE website = "The Constitution Society";
UPDATE think_tank_website set region = "美国", type = "智库", url = "http://www.thelugarcenter.org/" WHERE website = "The Lugar Center";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.stimson.org/" WHERE website = "The Stimson Center";
UPDATE think_tank_website set region = "澳大利亚", type = "智库", url = "N/A" WHERE website = "The Sydney Institute";
UPDATE think_tank_website set region = "印度", type = "智库", url = "https://takshashila.org.in/" WHERE website = "The Takshashila Institution";
UPDATE think_tank_website set region = "英国", type = "智库", url = "http://thewilberforcesociety.co.uk/" WHERE website = "The Wilberforce Society";
UPDATE think_tank_website set region = "爱尔兰", type = "智库", url = "https://www.tasc.ie/index.html" WHERE website = "Think Tank for Action on Social Change (TASC)";
UPDATE think_tank_website set region = "瑞典", type = "智库", url = "https://timbro.se/" WHERE website = "Timbro";
UPDATE think_tank_website set region = "日本", type = "智库", url = "https://www.tkfd.or.jp/en/about" WHERE website = "Tokyo Foundation";
UPDATE think_tank_website set region = "德国", type = "智库", url = "http://www.transparency.org" WHERE website = "Transparency International (TI)";
UPDATE think_tank_website set region = "菲律宾", type = "智库", url = "https://www.uap.asia/" WHERE website = "University of Asia and the Pacific";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://unlockdemocracy.org/" WHERE website = "Unlock Democracy";
UPDATE think_tank_website set region = "奥地利", type = "智库", url = "https://wiiw.ac.at/" WHERE website = "Vienna Institute for International Economic Studies (WIIW)";
UPDATE think_tank_website set region = "英国", type = "智库", url = "https://webrootsdemocracy.org/" WHERE website = "WebRoots Democracy";
UPDATE think_tank_website set region = "美国", type = "智库", url = "https://www.williamsmullen.com/" WHERE website = "Williams Mullen";
